project:
  type: website

website:
  title: "Lucas Couto"
  site-url: https://lucascoutoz.com
  description: "This is Lucas Couto's personal Blog."
  navbar:
    right:
      - text: Blog
        href: blog.qmd 
      - text: CV
        href: https://github.com/lucascoutoz/CV/blob/main/CV_Lucas_Couto.pdf
      - icon: twitter
        href: https://twitter.com/lucas_coutoz  
      - icon: github
        href: https://github.com/lucascoutoz
      
      
format:
  html:
    theme: journal
    css: styles.css

editor: visual

