project:
  type: website

website:
  title: "Lucas Couto"
  site-url: https://lucascoutoz.netlify.app/
  description: ""
  navbar:
    right:
      - text: Blog
        href: blog.qmd 
      - text: CV
        href: "cv/index.qmd"
      - icon: twitter
        href: https://twitter.com/lucas_coutoz  
      - icon: github
        href: https://github.com/lucascoutoz
  
format:
  html:
    theme: theme.scss


