project:
  type: website

website:
  title: "Lucas Couto"
  site-url: https://lucascoutoz.netlify.app/
  description: ""
  navbar:
    right:
      - text: Blog
        href: blog.qmd 
      - text: CV
        href: "cv/index.qmd"
      - text: "Research"
        file: research/index.qmd
      - icon: twitter
        href: https://twitter.com/lucas_coutoz  
      - icon: github
        href: https://github.com/lucascoutoz

  page-footer:
    left: "Powered by [Quarto](https://quarto.org/) and heavily based on [Andrew Heiss](https://www.andrewheiss.com/)."
    right: "Also, could not be made without [Bea Milz's](https://beamilz.com/posts/2022-06-05-creating-a-blog-with-quarto/en/) and [Albert Rapp's](https://albert-rapp.de/posts/13_quarto_blog_writing_guide/13_quarto_blog_writing_guide.html) tutorials."
     
  
format:
  html:
    theme: theme.scss


